### ISSUE TITLE
Details button glued to suggested packages desecription

### ISSUE THREAD

**Issue by Toflar** [contao/package-list#11]
<img width="734" alt="Bildschirmfoto 2024-04-24 um 10 23 47" src="https://github.com/contao/package-list/assets/481937/c7bafff5-0748-4bb9-9ef8-e7e3863f43ab">

Not sure if that's because of @zoglo's awesome contribution 😊 I love the new dark mode! ❤️

**Comment by zoglo** [comment]
Afaik, I didn't touch the package-link and details. I guess this has been like that for a while and only happens for specific breakpoints.
The package-link just needs a gap I guess.
