### ISSUE TITLE
Erweiterung als privates Paket falsch markiert

### ISSUE THREAD

**Issue by chwchw** [contao/package-list#3]
Die Erweiterung "Contao Encryption" wird als privates Paket markiert obwohl es nicht privat ist.
https://extensions.contao.org/?q=encrypyption%2Bbrk&pages=1

Der Datensatz scheint bereits von der Algoliasuche falsch zurückzukommen. Im Algoliadatensatz ist `private:true` gesetzt.
https://github.com/contao/package-list/blob/2d5584ff774012184b9a3f94083e69e3c9a51544/src/store/algolia.js#L176

**Comment by aschempp** [comment]
Dass das Paket von Algolia falsch kommt, liegt daran dass es vom Indexer aus irgend einem Grund falsch indexiert wird.
https://github.com/contao/package-metadata/

**Comment by aschempp** [comment]
see https://github.com/contao/package-metadata/pull/278
